# Generated by Django 4.2.17 on 2025-02-01 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='avatars/default_avatar.jpg', force_format='JPEG', keep_meta=False, quality=75, scale=None, size=[300, 300], upload_to='avatars/')),
                ('verified', models.BooleanField(default=False)),
                ('background', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=75, scale=None, size=[634, 200], upload_to='backgrounds/')),
                ('link', models.URLField(blank=True, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='follower', to='accounts.profile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
